export const GET_SUBSCRIBER = 'GET_SUBSCRIBER';
export const SUBSCRIBER_RECEIVED = 'SUBSCRIBER_RECEIVED';
export const SUBSCRIBER_REQUEST_FAILED = 'SUBSCRIBER_REQUEST_FAILED';

export const UPDATE_SUBSCRIBER = 'UPDATE_SUBSCRIBER';
export const UPDATE_SUBSCRIBER_SUCCESS = 'UPDATE_SUBSCRIBER_SUCCESS';
export const UPDATE_SUBSCRIBER_FAILED = 'UPDATE_SUBSCRIBER_FAILED';

export const CREATE_SUBSCRIBER = 'CREATE_SUBSCRIBER';
export const CREATE_SUBSCRIBER_SUCCESS = 'CREATE_SUBSCRIBER_SUCCESS';
export const CREATE_SUBSCRIBER_FAILED = 'CREATE_SUBSCRIBER_FAILED';